/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by @uni-ku/bundle-optimizer
export {}

interface ModuleMap {
  'three-platformize/examples/jsm/controls/OrbitControls': typeof import('three-platformize/examples/jsm/controls/OrbitControls')
  'three-platformize/examples/jsm/loaders/GLTFLoader': typeof import('three-platformize/examples/jsm/loaders/GLTFLoader')
  [path: string]: any
}

declare global {
  function AsyncImport<T extends keyof ModuleMap>(arg: T): Promise<ModuleMap[T]>
}
