/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Ccard: typeof import('./../../../src/components/common/Ccard/Ccard.vue')['default']
    Ccell: typeof import('./../../../src/components/common/Ccell/Ccell.vue')['default']
    Cerror: typeof import('./../../../src/components/common/Cerror/Cerror.vue')['default']
    CgcCol: typeof import('./../../../src/components/common/CgcCol/CgcCol.vue')['default']
    CgcRow: typeof import('./../../../src/components/common/CgcRow/CgcRow.vue')['default']
    Cgrid: typeof import('./../../../src/components/common/Cgrid/Cgrid.vue')['default']
    CgridCell: typeof import('./../../../src/components/common/CgridCell/CgridCell.vue')['default']
    CgridItem: typeof import('./../../../src/components/common/CgridItem/CgridItem.vue')['default']
    Cicon: typeof import('./../../../src/components/common/Cicon/Cicon.vue')['default']
    Clist: typeof import('./../../../src/components/common/Clist/Clist.vue')['default']
    ClistStatus: typeof import('./../../../src/components/common/ClistStatus/ClistStatus.vue')['default']
    CpageView: typeof import('./../../../src/components/common/CpageView/CpageView.vue')['default']
    CplusMinus: typeof import('./../../../src/components/common/CplusMinus/CplusMinus.vue')['default']
    CrequestList: typeof import('./../../../src/components/common/CrequestList/CrequestList.vue')['default']
    CstateTag: typeof import('./../../../src/components/common/CstateTag/CstateTag.vue')['default']
    CtabsFor: typeof import('./../../../src/components/common/CtabsFor/CtabsFor.vue')['default']
    Rbutton: typeof import('./../../../src/components/rewrite/Rbutton/Rbutton.vue')['default']
    Rcalendar: typeof import('./../../../src/components/rewrite/Rcalendar/Rcalendar.vue')['default']
    Rcheckbox: typeof import('./../../../src/components/rewrite/Rcheckbox/Rcheckbox.vue')['default']
    RcheckboxGroup: typeof import('./../../../src/components/rewrite/RcheckboxGroup/RcheckboxGroup.vue')['default']
    Rdivider: typeof import('./../../../src/components/rewrite/Rdivider/Rdivider.vue')['default']
    Rempty: typeof import('./../../../src/components/rewrite/Rempty/Rempty.vue')['default']
    Rimage: typeof import('./../../../src/components/rewrite/Rimage/Rimage.vue')['default']
    Rinput: typeof import('./../../../src/components/rewrite/Rinput/Rinput.vue')['default']
    RloadingIcon: typeof import('./../../../src/components/rewrite/RloadingIcon/RloadingIcon.vue')['default']
    RloadingPage: typeof import('./../../../src/components/rewrite/RloadingPage/RloadingPage.vue')['default']
    Rmodal: typeof import('./../../../src/components/rewrite/Rmodal/Rmodal.vue')['default']
    Rnotify: typeof import('./../../../src/components/rewrite/Rnotify/Rnotify.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Rpicker: typeof import('./../../../src/components/rewrite/Rpicker/Rpicker.vue')['default']
    Rpopup: typeof import('./../../../src/components/rewrite/Rpopup/Rpopup.vue')['default']
    Rradio: typeof import('./../../../src/components/rewrite/Rradio/Rradio.vue')['default']
    RradioGroup: typeof import('./../../../src/components/rewrite/RradioGroup/RradioGroup.vue')['default']
    Rslider: typeof import('./../../../src/components/rewrite/Rslider/Rslider.vue')['default']
    Rsticky: typeof import('./../../../src/components/rewrite/Rsticky/Rsticky.vue')['default']
    Rswiper: typeof import('./../../../src/components/rewrite/Rswiper/Rswiper.vue')['default']
    Rswitch: typeof import('./../../../src/components/rewrite/Rswitch/Rswitch.vue')['default']
    Rtabs: typeof import('./../../../src/components/rewrite/Rtabs/Rtabs.vue')['default']
    Rtag: typeof import('./../../../src/components/rewrite/Rtag/Rtag.vue')['default']
    Rtext: typeof import('./../../../src/components/rewrite/Rtext/Rtext.vue')['default']
    Rtransition: typeof import('./../../../src/components/rewrite/Rtransition/Rtransition.vue')['default']
  }
}
