/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CoAutoSquare: typeof import('./../../../src/components/common/CoAutoSquare/CoAutoSquare.vue')['default']
    CoCard: typeof import('./../../../src/components/common/CoCard/CoCard.vue')['default']
    CoCell: typeof import('./../../../src/components/common/CoCell/CoCell.vue')['default']
    CoDivider: typeof import('./../../../src/components/common/CoDivider/CoDivider.vue')['default']
    CoError: typeof import('./../../../src/components/common/CoError/CoError.vue')['default']
    CoGrid: typeof import('./../../../src/components/common/CoGrid/CoGrid.vue')['default']
    CoGridCell: typeof import('./../../../src/components/common/CoGridCell/CoGridCell.vue')['default']
    CoGridItem: typeof import('./../../../src/components/common/CoGridItem/CoGridItem.vue')['default']
    CoIcon: typeof import('./../../../src/components/common/CoIcon/CoIcon.vue')['default']
    CoList: typeof import('./../../../src/components/common/CoList/CoList.vue')['default']
    CoListStatus: typeof import('./../../../src/components/common/CoListStatus/CoListStatus.vue')['default']
    CoNotify: typeof import('./../../../src/components/common/CoNotify/CoNotify.vue')['default']
    CoPageView: typeof import('./../../../src/components/common/CoPageView/CoPageView.vue')['default']
    CoPlusMinus: typeof import('./../../../src/components/common/CoPlusMinus/CoPlusMinus.vue')['default']
    CoRequestList: typeof import('./../../../src/components/common/CoRequestList/CoRequestList.vue')['default']
    CoStateTag: typeof import('./../../../src/components/common/CoStateTag/CoStateTag.vue')['default']
    CoStepsItem: typeof import('./../../../src/components/common/CoTimerShaftItem/CoStepsItem.vue')['default']
    CoTabsFor: typeof import('./../../../src/components/common/CoTabsFor/CoTabsFor.vue')['default']
    CoTimerShaft: typeof import('./../../../src/components/common/CoTimerShaftItem/CoTimerShaft.vue')['default']
    CoTimerShaftItem: typeof import('./../../../src/components/common/CoTimerShaftItem/CoTimerShaftItem.vue')['default']
    ReImage: typeof import('./../../../src/components/rewrite/ReImage/ReImage.vue')['default']
    ReInput: typeof import('./../../../src/components/rewrite/ReInput/ReInput.vue')['default']
    ReTabs: typeof import('./../../../src/components/rewrite/ReTabs/ReTabs.vue')['default']
  }
}
