/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CoAutoSquare: typeof import('./../../../src/components/common/CoAutoSquare/CoAutoSquare.vue')['default']
    CoCard: typeof import('./../../../src/components/common/CoCard/CoCard.vue')['default']
    CoCascader: typeof import('./../../../src/components/common/CoCascader/CoCascader.vue')['default']
    CoCell: typeof import('./../../../src/components/common/CoCell/CoCell.vue')['default']
    CoCheckBoxBtn: typeof import('./../../../src/components/common/CoCheckBoxBtn/CoCheckBoxBtn.vue')['default']
    CoCollapse: typeof import('./../../../src/components/common/CoCollapse/CoCollapse.vue')['default']
    CoDivider: typeof import('./../../../src/components/common/CoDivider/CoDivider.vue')['default']
    CoDropdown: typeof import('./../../../src/components/common/CoDropdown/CoDropdown.vue')['default']
    CoError: typeof import('./../../../src/components/common/CoError/CoError.vue')['default']
    CoGrid: typeof import('./../../../src/components/common/CoGrid/CoGrid.vue')['default']
    CoGridCell: typeof import('./../../../src/components/common/CoGridCell/CoGridCell.vue')['default']
    CoGridItem: typeof import('./../../../src/components/common/CoGridItem/CoGridItem.vue')['default']
    CoIcon: typeof import('./../../../src/components/common/CoIcon/CoIcon.vue')['default']
    CoList: typeof import('./../../../src/components/common/CoList/CoList.vue')['default']
    CoListStatus: typeof import('./../../../src/components/common/CoListStatus/CoListStatus.vue')['default']
    CoMap: typeof import('./../../../src/components/common/CoMap/CoMap.vue')['default']
    CoNotify: typeof import('./../../../src/components/common/CoNotify/CoNotify.vue')['default']
    CoPageView: typeof import('./../../../src/components/common/CoPageView/CoPageView.vue')['default']
    CoPlusMinus: typeof import('./../../../src/components/common/CoPlusMinus/CoPlusMinus.vue')['default']
    CoRequestList: typeof import('./../../../src/components/common/CoRequestList/CoRequestList.vue')['default']
    CoSelect: typeof import('./../../../src/components/common/CoSelect/CoSelect.vue')['default']
    CoSortControl: typeof import('./../../../src/components/common/CoSortControl/CoSortControl.vue')['default']
    CoStateTag: typeof import('./../../../src/components/common/CoStateTag/CoStateTag.vue')['default']
    CoStepLine: typeof import('./../../../src/components/common/CoStepLine/CoStepLine.vue')['default']
    CoTabsFor: typeof import('./../../../src/components/common/CoTabsFor/CoTabsFor.vue')['default']
    CoVideo: typeof import('./../../../src/components/common/CoVideo/CoVideo.vue')['default']
    CoWebView: typeof import('./../../../src/components/common/CoWebView/CoWebView.vue')['default']
    EnvCoverImage: typeof import('./../../../src/components/common/CoMap/envCoverImage.vue')['default']
    EnvCoverView: typeof import('./../../../src/components/common/CoMap/envCoverView.vue')['default']
    GrFilterSearch: typeof import('./../../../src/components/group/GrFilterSearch/GrFilterSearch.vue')['default']
    NaUpload: typeof import('./../../../src/components/native/NaUpload/NaUpload.vue')['default']
    NaVideo: typeof import('./../../../src/components/native/NaVideo/NaVideo.vue')['default']
    ReUpload: typeof import('./../../../src/components/rewrite/ReUpload/ReUpload.vue')['default']
  }
}
