/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Cerror: typeof import('./../../src/components/common/Cerror/Cerror.vue')['default']
    Clist: typeof import('./../../src/components/common/Clist/Clist.vue')['default']
    ClistStatus: typeof import('./../../src/components/common/ClistStatus/ClistStatus.vue')['default']
    CpageView: typeof import('./../../src/components/common/CpageView/CpageView.vue')['default']
    CrequestList: typeof import('./../../src/components/common/CrequestList/CrequestList.vue')['default']
    CtabsFor: typeof import('./../../src/components/common/CtabsFor/CtabsFor.vue')['default']
    Rbutton: typeof import('./../../src/components/rewrite/Rbutton/Rbutton.vue')['default']
    Rcalendar: typeof import('./../../src/components/rewrite/Rcalendar/Rcalendar.vue')['default']
    Rdivider: typeof import('./../../src/components/rewrite/Rdivider/Rdivider.vue')['default']
    Rempty: typeof import('./../../src/components/rewrite/Rempty/Rempty.vue')['default']
    Rimage: typeof import('./../../src/components/rewrite/Rimage/Rimage.vue')['default']
    Rinput: typeof import('./../../src/components/rewrite/Rinput/Rinput.vue')['default']
    Rloading: typeof import('./../../src/components/rewrite/Rloading/Rloading.vue')['default']
    RloadingIcon: typeof import('./../../src/components/rewrite/RloadingIcon/RloadingIcon.vue')['default']
    RloadingPage: typeof import('./../../src/components/rewrite/RloadingPage/RloadingPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Rpicker: typeof import('./../../src/components/rewrite/Rpicker/Rpicker.vue')['default']
    Rsticky: typeof import('./../../src/components/rewrite/Rsticky/Rsticky.vue')['default']
    Rswiper: typeof import('./../../src/components/rewrite/Rswiper/Rswiper.vue')['default']
    Rtabs: typeof import('./../../src/components/rewrite/Rtabs/Rtabs.vue')['default']
    Rtag: typeof import('./../../src/components/rewrite/Rtag/Rtag.vue')['default']
    Rtext: typeof import('./../../src/components/rewrite/Rtext/Rtext.vue')['default']
    Rtransition: typeof import('./../../src/components/rewrite/Rtransition/Rtransition.vue')['default']
  }
}
