/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    "u-collapse": typeof import("./components/collapse.vue")["default"];
    "u-collapse-item": typeof import("./components/collapseItem.vue")["default"];
    "u-radio": typeof import("./components/radio.vue")["default"];
    "u-radio-group": typeof import("./components/radioGroup.vue")["default"];
    "u-checkbox": typeof import("./components/checkbox.vue")["default"];
    "u-checkbox-group": typeof import("./components/checkboxGroup.vue")["default"];
  }
}
