export type Mode =
  | "aspectFill"
  | "scaleToFill"
  | "aspectFit"
  | "widthFix"
  | "heightFix"
  | "top"
  | "bottom"
  | "center"
  | "center"
  | "right"
  | "top left"
  | "top right"
  | "bottom left"
  | "bottom right";
