/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Mbutton: typeof import('./../../components/rewrite/Mbutton.vue')['default']
    MImage: typeof import('./../../components/rewrite/MImage.vue')['default']
    MInput: typeof import('./../../components/rewrite/MInput.vue')['default']
    Mtext: typeof import('./../../components/rewrite/Mtext.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
