/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Bh1: typeof import('./../../components/base/Bh1.vue')['default']
    Bh2: typeof import('./../../components/base/Bh2.vue')['default']
    Bh3: typeof import('./../../components/base/Bh3.vue')['default']
    Bh4: typeof import('./../../components/base/Bh4.vue')['default']
    Bh5: typeof import('./../../components/base/Bh5.vue')['default']
    CpageView: typeof import('./../../components/common/CpageView.vue')['default']
    Ctabs: typeof import('./../../components/common/Ctabs/Ctabs.vue')['default']
    CtabsItem: typeof import('./../../components/common/Ctabs/CtabsItem.vue')['default']
    Rbutton: typeof import('./../../components/rewrite/Rbutton.vue')['default']
    Rimage: typeof import('./../../components/rewrite/Rimage.vue')['default']
    Rinput: typeof import('./../../components/rewrite/Rinput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Rtext: typeof import('./../../components/rewrite/Rtext.vue')['default']
  }
}
