/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Mbutton: typeof import('./../../components/rewrite/Mbutton.vue')['default']
    Mh1: typeof import('./../../components/base/Mh1.vue')['default']
    Mh2: typeof import('./../../components/base/Mh2.vue')['default']
    Mh3: typeof import('./../../components/base/Mh3.vue')['default']
    Mh4: typeof import('./../../components/base/Mh4.vue')['default']
    Mh5: typeof import('./../../components/base/Mh5.vue')['default']
    Mimage: typeof import('./../../components/rewrite/Mimage.vue')['default']
    Minput: typeof import('./../../components/rewrite/Minput.vue')['default']
    Mtext: typeof import('./../../components/rewrite/Mtext.vue')['default']
    PageView: typeof import('./../../components/base/PageView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
