/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    "u-collapse": typeof import("./components/Rcollapse/Rcollapse.vue")["default"];
    "u-collapse-item": typeof import("./components/RcollapseItem/RcollapseItem.vue")["default"];
    "u-radio": typeof import("./components/Rradio/Rradio.vue")["default"];
    "u-radio-group": typeof import("./components/RradioGroup/RradioGroup.vue")["default"];
    "u-checkbox": typeof import("./components/Rcheckbox/Rcheckbox.vue")["default"];
    "u-checkbox-group": typeof import("./components/RcheckboxGroup/RcheckboxGroup.vue")["default"];
    "u-swipe-action": typeof import("./components/RswipeActionGroup/RswipeActionGroup.vue")["default"];
  }
}
